permalink: /:title/
title: Zhong Zhong # your name (or website title) here
logo: "/images/lihai.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>
    <br> I'm graduate student who has a strong interest in Machine Learning and Data Analysis. I also study Deep Learning (especially, computer vision) during my free time. <br>
    
    <br>笨鸟先飞 & 耐心
  </p>
  <a href="https://www.linkedin.com/in/zhong-zhong-01517717b/">My LinkedIn Profile</a> 
social-network-links:
  twitter: zhongzhong2 
  linkedin: zhong-zhong-01517717b 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

